name: Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: 显示当前目录结构
      run: |
        echo "当前目录结构："
        ls -R

    - name: 压缩插件文件
      run: |
        if [ -d "amusementbreak/Latest-posts" ]; then
          cd amusementbreak/Latest-posts
          zip -r ../../latest-posts-for-elementor.zip .
          cd ../..
        else
          echo "错误：未找到插件目录 amusementbreak/Latest-posts"
          echo "当前目录结构："
          ls -R
          exit 1
        fi

    - name: 检查 zip 文件
      run: |
        if [ ! -f "latest-posts-for-elementor.zip" ]; then
          echo "错误：未找到 zip 文件"
          exit 1
        fi

    - name: 创建 Release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        tag_name="${GITHUB_REF#refs/tags/}"
        release_name="Release $tag_name"
        gh release create "$tag_name" \
          --title "$release_name" \
          --notes "latest-posts-for-elementor $tag_name" \
          "./latest-posts-for-elementor.zip#Latest Posts for Elementor"

    - name: 清理
      if: always()
      run: rm -f latest-posts-for-elementor.zip