name: Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # 使用较新的 Node.js 版本

    - name: 压缩插件文件
      run: |
        if [ -d "amusementbreak/Latest-posts" ]; then
          cd amusementbreak/Latest-posts
          zip -r ../../latest-posts-for-elementor.zip .
          cd ../..
        else
          echo "错误：未找到插件目录 amusementbreak/Latest-posts"
          echo "当前目录结构："
          ls -R
          exit 1
        fi

    - name: 检查 zip 文件
      run: |
        if [ ! -f "latest-posts-for-elementor.zip" ]; then
          echo "错误：未找到 zip 文件"
          exit 1
        fi

    - name: 获取版本号
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: 检查 Release 是否存在
      id: check_release
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.get_version.outputs.VERSION }})
        if [ $response -eq 200 ]; then
          echo "RELEASE_EXISTS=true" >> $GITHUB_OUTPUT
        else
          echo "RELEASE_EXISTS=false" >> $GITHUB_OUTPUT
        fi

    - name: 创建 Release
      id: create_release
      if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: 上传 Release 资产
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./latest-posts-for-elementor.zip
        asset_name: latest-posts-for-elementor.zip
        asset_content_type: application/zip

    - name: 清理
      if: always()
      run: rm -f latest-posts-for-elementor.zip